export const LOAD_MORE_IMAGES = 'LOAD_MORE_IMAGES';
export const RESET_IMAGES_NUMBER = 'RESET_IMAGES_NUMBER';
export const CHANGE_RENDERTITLE = 'CHANGE_RENDERTITLE';
export const RESET_RENDERTITLE = 'RESET_RENDERTITLE';
export const CHANGE_CURRENTPAGE = 'CHANGE_CURRENTPAGE';
export const RESET_CURRENTPAGE = 'RESET_CURRENTPAGE';
