export const CHANGE_ALBUMNUMBER = 'CHANGE_ALBUMNUMBER';
export const RESET_ALBUMNUMBER = 'RESET_ALBUMNUMBER';
export const CHANGE_TRACKNUMBER = 'CHANGE_TRACKNUMBER';
export const RESET_TRACKNUMBER = 'RESET_TRACKNUMBER';